config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'dashboard/index'
  end

  devise_for :admins
  namespace :users do
    get 'dashboard/index'
  end

  root to: 'home#index'

  devise_for :users

  authenticate :user do
    namespace :users do
      root to: 'dashboard#index'

      get 'lists/:id/share', to: "lists#share", as: :new_share_list
      post 'lists/:id/share', to: "lists#share_with", as: :share_list

      get 'auto-complete-search', to: "users#index", as: :autocomplete_search

      resources :lists, except: :index do
        patch 'tasks/:id/completed', to: 'tasks#completed', as: :mark_task_as_completed
        patch 'tasks/:id/uncompleted', to: 'tasks#uncompleted', as: :mark_task_as_uncompleted
        resources :tasks, except: :index
      end
    end
  end

  authenticate :admin do
    namespace :admins do
      root to: 'dashboard#index'
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable

  def name
    'Administrador'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :tasks

  has_many :users_lists
  has_many :shared_users, through: :users_lists, source: :user

  validates :name, presence: true, uniqueness: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  validates :title, presence: true

  scope :completed, -> { where(done: true) }
  scope :uncompleted, -> { where(done: false) }

  def mark_as_completed
    update_attribute(:done, true)
  end

  def mark_as_uncompleted
    update_attribute(:done, false)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists

  has_many :users_lists
  has_many :shared_lists, through: :users_lists, source: :list

  validates :name, presence: true

  def self.search(query)
    order(:name).where("name ilike ?", "%#{query}%")
  end
end

app/models/users_list.rb
class UsersList < ApplicationRecord
  belongs_to :list
  belongs_to :user
end

app/controllers/admins/base_controller.rb
class Admins::BaseController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'admins/layouts/application'
end

app/controllers/admins/dashboard_controller.rb
class Admins::DashboardController < Admins::BaseController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  layout :layout_by_resource

  protected
  def layout_by_resource
    if devise_controller?
      if resource_name == :user && ['edit', 'update'].include?(action_name)
        "users/layouts/application"
      elsif resource_name == :admin && !(['new', 'create'].include?(action_name))
      "admins/layouts/application"
      else
        "layouts/session"
      end
    else
      "layouts/application"
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    return admins_root_path if resource.is_a? Admin
    users_root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
      new_user_session_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/base_controller.rb
class Users::BaseController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'users/layouts/application'
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < Users::BaseController
  def index
  end
end

app/controllers/users/lists_controller.rb
class Users::ListsController < Users::BaseController

  def new
    @list = current_user.lists.new
  end

  def create
    @list = current_user.lists.new(list_parms)

    if @list.save
      flash[:success] = "Lista criada com sucesso!"
      redirect_to users_list_path(@list)
    else
      flash[:error] = "Existem dados incorretos! Por favor verifique."
      render :new
    end
  end

  def show
    @list = current_user.lists.find_by(id: params[:id]) ||
        current_user.shared_lists.find(params[:id])

    @tasks_completed = @list.tasks.completed
    @tasks_uncompleted = @list.tasks.uncompleted
  end

  def share
    @list = current_user.lists.find(params[:id])
  end

  def share_with
    @user = User.find(params[:user_id])
    @list = current_user.lists.find(params[:id])

    @list.shared_users << @user
    redirect_to users_share_list_path(@list)
  end

  private
  def list_parms
    params.require(:list).permit(:name)
  end

end

app/controllers/users/tasks_controller.rb
class Users::TasksController < Users::BaseController
  skip_before_action :verify_authenticity_token, only: [:completed, :uncompleted]
  before_action :load_list

  def create
    @task = @list.tasks.new(task_parms)

    if @task.save
      flash[:success] = "Tarefa criada com sucesso!"
    else
      flash[:error] = "Não foi possível criar a tarefa"
    end

    redirect_to users_list_path(@list)
  end

  def completed
    @task = @list.tasks.find(params[:id])
    @task.mark_as_completed
  end

  def uncompleted
    @task = @list.tasks.find(params[:id])
    @task.mark_as_uncompleted
  end

  private
  def load_list
    @list = current_user.lists.find_by(id: params[:list_id]) ||
        current_user.shared_lists.find(params[:list_id])
  end

  def task_parms
    params.require(:task).permit(:title)
  end

end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
  def index
    @users = User.search(params[:query])
    render json: @users.map {|u| {data: u.id, value: u.name} }
  end
end

app/helpers/admins/base_helper.rb
module Admins::BaseHelper
end

app/helpers/admins/dashboard_helper.rb
module Admins::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: 'alert-success', error: 'alert-danger', alert: 'alert-warning',
      notice: 'alert-info' }[flash_type.to_sym] || flash_type.to_s
  end

  def full_title(page_title = '', base_title = 'Bucketlist')
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/helpers/users/lists_helper.rb
module Users::ListsHelper
end

app/helpers/users/tasks_helper.rb
module Users::TasksHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/admins/dashboard/index.html.erb
<h1>Área do administrativa</h1>

app/views/users/dashboard/index.html.erb
<h1>Área do usuário autenticado</h1>

app/views/users/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-gray">

  <%= link_to "Bucketlist", root_path, class: "nav-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'Dashboard', users_root_path, class: 'nav-link' %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'Meu perfil', edit_user_registration_path,
                        class: 'dropdown-item' %>
            <%= link_to 'Sair', destroy_user_session_path, method: :delete,
                        class: 'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Entrar', new_user_session_path,
                      class: 'btn btn-primary btn-sm' %>
        </li>
      <% end %>
    </ul>
  </div>

</nav>

app/views/users/layouts/_sidebar.html.erb
<ul class="nav nav-pills flex-column">
  <% current_user.reload.lists.each do |list| %>
    <li class="nav-item clearfix">
      <%= link_to list.name, users_list_path(list), class: 'nav-link float-left' %>
      <%= link_to users_new_share_list_path(list), class: 'nav-link float-right' do %>
        <i class="fa fa-share" aria-hidden="true"></i>
      <% end %>
    </li>
  <% end %>
</ul>

<hr />

<h6 class="text-center">Compartilhadas</h6>

<ul class="nav nav-pills flex-column">
  <% current_user.shared_lists.each do |list| %>
    <li class="nav-item">
      <%= link_to list.name, users_list_path(list), class: 'nav-link' %>
    </li>
  <% end %>
</ul>

<div class='fixed-bottom'>
  <%= link_to '+', new_users_list_path, class: 'btn btn-primary btn-lg col-sm-3 col-md-2' %>
</div>

app/views/users/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title><%= full_title(yield(:head_title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'users/application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'users/application', 'data-turbolinks-track': 'reload' %>

  <%= render 'layouts/shim' %>

</head>
<body id="<%= controller_name %>_<%= action_name %>">

<%= render 'users/layouts/navbar' %>

<div class="container-fluid">
  <div class="row">

    <div class="col-sm-3 col-md-2 sidebar">
      <%= render 'users/layouts/sidebar' %>
    </div>

    <div class="col-sm-9 ml-sm-auto col-md-10">
      <%= render 'shared/flash_messages' %>
      <%= yield %>
    </div>

  </div>
</div>

</body>
</html>

app/views/users/lists/new.html.erb
<h1>Nova lista</h1>

<%= simple_form_for(@list, url: users_lists_path) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Enviar", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/lists/share.html.erb
<h1 class='mt-sm-2'>Compartilhar lista <%= @list.name %></h1>

<%= form_with(url: users_share_list_path, html: {class: 'form-inline'}) do |f| %>

  <%= f.hidden_field :user_id, id: 'autocomplete_user_by_id' %>
  <div class="form-group mr-sm-1">
    <%= f.text_field :user_name, id: 'autocomplete_user_by_name', 'data-url' => users_autocomplete_search_path, class: 'form-control' %>
  </div>
  <%= f.submit "Enviar", class: 'btn btn-primary' %>
<% end %>

<br />

<h3>Compartilhado com</h3>

<ul>
  <% @list.shared_users.each do |u|%>
    <li><%= "#{u.name} <#{u.email}>" %> </li>
  <% end %>
</ul>

app/views/users/lists/show.html.erb
<h1><%= @list.name %></h1>

<%= simple_form_for(:task, url: users_list_tasks_path(@list), html: {class: 'form-inline'}) do |f| %>
  <%= f.input :title, input_html: {class: 'col-md-12'}, wrapper_html: {class: 'col-md-10'}, label: false, placeholder: "Adicione uma tarefa em \"#{@list.name}\""  %>
  <%= f.button :submit, "Enviar", class: 'btn btn-primary col-md-2' %>
<% end %>

<br>
<hr>
<br>

<div class="row">
  <div class="col-md-6">
    <h3>Tarefas pendentes</h3>

    <ul id="tasks_uncompleted" class="list-group">
      <%= render @tasks_uncompleted, url: :users_list_mark_task_as_completed_path  %>
    </ul>
  </div>

  <div class="col-md-6">

    <h3>Tarefas concluídas</h3>

    <ul id="tasks_completed" class="list-group">
      <%= render @tasks_completed, url: :users_list_mark_task_as_uncompleted_path %>
    </ul>
  </div>
</div>

app/views/users/tasks/_task.html.erb
<li class="list-group-item">
  <div class="form-check">
    <input  update-task-status-url="<%= send(url, @list, task) %>" type="checkbox"
            data-status=<%= task.done? %> class="form-check-input">
    <label class="form-check-label" for="exampleCheck1"><%= task.title %></label>
  </div>
</li>





<!--<label class="custom-control custom-checkbox">
  <input update-task-status-url="<%#= send(url, @list, task) %>" type="checkbox"
         data-status=<%#= task.done? %> class="custom-control-input" >
  <span class="custom-control-indicator"></span>
  <span class="custom-control-description"><%#= task.title %></span>
</label>-->