config/routes.rb
Rails.application.routes.draw do
  namespace :admins do
    get 'dashboard/index'
  end

  devise_for :admins
  namespace :users do
    get 'dashboard/index'
  end

  root to: 'home#index'

  devise_for :users

  authenticate :user do
    namespace :users do
      root to: 'dashboard#index'

      get 'lists/:id/share', to: "lists#share", as: :new_share_list
      post 'lists/:id/share', to: "lists#share_with", as: :share_list

      get 'auto-complete-search', to: "users#index", as: :autocomplete_search

      resources :lists, except: :index do
        patch 'tasks/:id/completed', to: 'tasks#completed', as: :mark_task_as_completed
        patch 'tasks/:id/uncompleted', to: 'tasks#uncompleted', as: :mark_task_as_uncompleted
        resources :tasks, except: :index
      end
    end
  end

  authenticate :admin do
    namespace :admins do
      root to: 'dashboard#index'
    end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable,
         :rememberable, :trackable, :validatable

  def name
    'Administrador'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :tasks

  has_many :users_lists
  has_many :shared_users, through: :users_lists, source: :user

  validates :name, presence: true, uniqueness: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list

  validates :title, presence: true

  scope :completed, -> { where(done: true) }
  scope :uncompleted, -> { where(done: false) }

  def mark_as_completed
    update_attribute(:done, true)
  end

  def mark_as_uncompleted
    update_attribute(:done, false)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists

  has_many :users_lists
  has_many :shared_lists, through: :users_lists, source: :list

  validates :name, presence: true

  def self.search(query)
    order(:name).where("name ilike ?", "%#{query}%")
  end
end

app/models/users_list.rb
class UsersList < ApplicationRecord
  belongs_to :list
  belongs_to :user
end

app/controllers/admins/base_controller.rb
class Admins::BaseController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'admins/layouts/application'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  layout :layout_by_resource

  protected
  def layout_by_resource
    if devise_controller?
      if resource_name == :user && ['edit', 'update'].include?(action_name)
        "users/layouts/application"
      elsif resource_name == :admin && !(['new', 'create'].include?(action_name))
      "admins/layouts/application"
      else
        "layouts/session"
      end
    else
      "layouts/application"
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_in_path_for(resource)
    return admins_root_path if resource.is_a? Admin
    users_root_path
  end

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
      new_user_session_path
    elsif resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/base_controller.rb
class Users::BaseController < ActionController::Base
  protect_from_forgery with: :exception
  layout 'users/layouts/application'
end

app/controllers/users/lists_controller.rb
class Users::ListsController < Users::BaseController

  def new
    @list = current_user.lists.new
  end

  def create
    @list = current_user.lists.new(list_parms)

    if @list.save
      flash[:success] = "Lista criada com sucesso!"
      redirect_to users_list_path(@list)
    else
      flash[:error] = "Existem dados incorretos! Por favor verifique."
      render :new
    end
  end

  def show
    @list = current_user.lists.find_by(id: params[:id]) ||
        current_user.shared_lists.find(params[:id])

    @tasks_completed = @list.tasks.completed
    @tasks_uncompleted = @list.tasks.uncompleted
  end

  def share
    @list = current_user.lists.find(params[:id])
  end

  def share_with
    @user = User.find(params[:user_id])
    @list = current_user.lists.find(params[:id])

    @list.shared_users << @user
    redirect_to users_share_list_path(@list)
  end

  private
  def list_parms
    params.require(:list).permit(:name)
  end

end

app/controllers/users/tasks_controller.rb
class Users::TasksController < Users::BaseController
  skip_before_action :verify_authenticity_token, only: [:completed, :uncompleted]
  before_action :load_list

  def create
    @task = @list.tasks.new(task_parms)

    if @task.save
      flash[:success] = "Tarefa criada com sucesso!"
    else
      flash[:error] = "Não foi possível criar a tarefa"
    end

    redirect_to users_list_path(@list)
  end

  def completed
    @task = @list.tasks.find(params[:id])
    @task.mark_as_completed
  end

  def uncompleted
    @task = @list.tasks.find(params[:id])
    @task.mark_as_uncompleted
  end

  private
  def load_list
    @list = current_user.lists.find_by(id: params[:list_id]) ||
        current_user.shared_lists.find(params[:list_id])
  end

  def task_parms
    params.require(:task).permit(:title)
  end

end

app/helpers/admins/base_helper.rb
module Admins::BaseHelper
end

app/helpers/admins/dashboard_helper.rb
module Admins::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: 'alert-success', error: 'alert-danger', alert: 'alert-warning',
      notice: 'alert-info' }[flash_type.to_sym] || flash_type.to_s
  end

  def full_title(page_title = '', base_title = 'Bucketlist')
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/helpers/users/lists_helper.rb
module Users::ListsHelper
end

app/helpers/users/tasks_helper.rb
module Users::TasksHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/admins/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-black">

  <%= link_to "Bucketlist", root_path, class: "nav-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'Dashboard', admins_root_path, class: 'nav-link' %>
      </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_admin.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'Sair', destroy_admin_session_path, method: :delete,
                        class: 'dropdown-item' %>
          </div>
        </li>

    </ul>
  </div>

</nav>

app/views/admins/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title><%= full_title(yield(:head_title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'admins/application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'admins/application', 'data-turbolinks-track': 'reload' %>

  <%= render 'layouts/shim' %>

</head>
<body>

<%= render 'admins/layouts/navbar' %>

<div class="container">
  <%= render 'shared/flash_messages' %>
  <%= yield %>
</div>

</body>
</html>

app/views/layouts/_footer.html.erb
<footer class="footer bg-light">
  <div class="container text-center">
    <span class="text-muted">Created by Diego Marczal to WD5 course - Copyright 2017 ©</span>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <%= link_to "Bucketlist", root_path, class: "nav-brand" %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'Página Inicial', root_path, class: 'nav-link' %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to 'Meu perfil', edit_user_registration_path,
                        class: 'dropdown-item' %>
            <%= link_to 'Sair', destroy_user_session_path, method: :delete,
                        class: 'dropdown-item' %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Entrar', new_user_session_path,
                      class: 'btn btn-primary btn-sm' %>
        </li>
      <% end %>
    </ul>
  </div>

</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title><%= full_title(yield(:head_title)) %></title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <%= render 'layouts/shim' %>

</head>
<body>

<%= render 'layouts/navbar' %>

<div class="container">
  <%= render 'shared/flash_messages'%>
  <%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>

app/views/layouts/session.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:head_title)) %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'session', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'session',
                             'data-turbolinks-track': 'reload' %>
</head>

<body>

<%= render 'layouts/navbar' %>

<div id="<%= controller_name %>-<%= action_name %>" class="container">
  <div class="vertical-centering horizontal-centering">
    <%= render 'shared/flash_messages'%>

    <div>
      <h3 class="text-center gray-text2"><%= yield :title %></h3>
      <p class="gray-text2"><%= yield :sub_title %></p>
    </div>
    <%= yield %>

  </div> <!-- .vertical-centering .horizontal-centering -->
</div> <!-- #home-index -->

</body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade show" role="alert">
    <button class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= message %>
  </div>
<% end %>